name: Update sub Nodes

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update_nodes:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 获取最新的节点信息
        run: |
          curl -sSL "https://raw.githubusercontent.com/go4sharing/sub/refs/heads/main/sub.yam" -o nodes.yaml

      - name: 提取并格式化节点信息
        run: |
          echo "proxies:" > v2ray/sub.yaml
          awk '/proxies:/,/^$/' nodes.yaml | tail -n +2 >> v2ray/sub.yaml

      - name: 配置 Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 提交更新
        run: |
          git add v2ray/sub.yaml
          git commit -m "自动更新 V2Ray 节点信息"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
