name: Update Subscription Nodes

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  simple-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yq v4
        run: |
          curl -fsSL https://install.yq.sh | sh -s -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Fetch raw nodes
        run:
          curl -fsSL "https://raw.githubusercontent.com/go4sharing/sub/refs/heads/main/sub.yaml" -o raw_nodes.txt

      - name: Prepend 'proxies:' to the top
        run: |
          # 确保首行是 'proxies:'，其余内容保留原始格式
          echo "proxies:" > sub.yaml
          cat raw_nodes.txt >> sub.yaml

      - name: Validate and commit
        run: |
          if [ -z "$(grep 'proxies:' sub.yaml)" ] || [ $(wc -l < sub.yaml) -le 1 ]; then
            echo "Error: No nodes found after prepend"
            exit 1
          fi
          git config user.name "Actions"
          git config user.email "actions@github.com"
          git add sub.yaml
          git commit -m "Add proxies: header $(date +'%Y-%m-%d %H:%M')" -a || true
          git push
