name: Update Subscription Nodes

on:
  schedule:
    - cron: "0 */2 * * *"  # 每两小时执行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  fetch-nodes-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and parse proxies
        run: |
          # 下载原始文件
          curl -fsSL "https://raw.githubusercontent.com/go4sharing/sub/refs/heads/main/sub.yaml" -o raw_sub.yaml
          
          # 提取proxies节点组（使用awk过滤非proxies行，保留YAML格式）
          awk '/^proxies:/,/^- name:/ { if (/^proxies:/) { print; flag=1; } else if (/^[a-z]/ && flag) { exit; } else { print; } }' raw_sub.yaml > nodes_only.yaml
          
          # 验证节点组是否有效
          if [ ! -s nodes_only.yaml ] || [ "$(grep 'name:' nodes_only.yaml)" ]; then
            echo "Error: No valid nodes found"
            exit 1
          fi

      - name: Save as sub.yaml
        run: |
          mv nodes_only.yaml ./sub.yaml
          echo "Successfully updated nodes group to sub.yaml"

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sub.yaml
          git commit -m "Update nodes group $(date +'%Y-%m-%d %H:%M:%S')" -a || true
          git push
