name: Update Subscription Nodes

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  fetch-nodes-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yq (YAML parser)
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Fetch raw sub.yaml
        run: |
          curl -fsSL "https://raw.githubusercontent.com/go4sharing/sub/refs/heads/main/sub.yaml" -o raw_sub.yaml
          cat raw_sub.yaml  # 打印原始内容以便调试

      - name: Extract proxies array
        run: |
          # 使用yq提取proxies数组并格式化为YAML
          yq eval '.proxies | to_yaml' raw_sub.yaml > nodes_only.yaml

      - name: Validate nodes
        run: |
          if [ ! -s nodes_only.yaml ] || [ "$(yq eval 'length' nodes_only.yaml)" -eq 0 ]; then
            echo "Error: No valid nodes found in the file"
            cat nodes_only.yaml  # 打印空文件内容
            exit 1
          fi

      - name: Save as sub.yaml
        run:
          mv nodes_only.yaml ./sub.yaml

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sub.yaml
          git commit -m "Update nodes group $(date +'%Y-%m-%d %H:%M:%S')" -a || true
          git push
