name: Update Gist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Update Gist
        uses: crazy-max/ghaction-gist@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: adf2e62a5931358889eca20256cd0833  # 你的 Gist ID
          files: |
            v2ray/data/all.yaml  # 要上传的文件路径
          description: Auto-updated Gist by GitHub Actions
