name: Update Gist

on:
  schedule:
    # 每天 UTC 时间 0 点运行
    - cron: '0 0 * * *'
  # 也可以手动触发工作流
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Gist via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: adf2e62a5931358889eca20256cd0833
          FILENAME: data/all.yaml
          GIST_DESCRIPTION: Auto-updated Gist
        run: |
          # 读取文件内容
          FILE_CONTENT=$(cat $FILENAME)
          # 构建 JSON 数据
          JSON_DATA=$(jq -n --arg desc "$GIST_DESCRIPTION" --arg filename "$FILENAME" --arg content "$FILE_CONTENT" '{description: $desc, files: {($filename): {content: $content}}}')
          # 调用 GitHub API 更新 Gist
          curl -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$JSON_DATA" \
            "https://api.github.com/gists/$GIST_ID"
