name: 自动更新 all.yaml 文件

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 执行（北京时间 08:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: 检查仓库
        uses: actions/checkout@v4
        
      - name: 下载最新 YAML 文件
        run: |
          curl -L -o data/all.yaml https://gist.githubusercontent.com/dalazhi/d0db537c55d15ba97c80d169bd00bbb7/raw/all.yaml
          echo "下载完成"
          
      - name: 检查文件是否有更新
        id: check_diff
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "文件有更新"
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "文件无更新"
            echo "has_changes=false" >> $GITHUB_ENV
          fi
          
      - name: 提交更新
        if: env.has_changes == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/all.yaml
          git commit -m "自动更新 all.yaml 文件"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
